version: 2
jobs:
  #  build and test jobs go here
  deploy-job:
    docker:
      - image: my-image
    working_directory: /tmp/my-project
    steps:
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync drewtestingsite s3://drewtestingsite --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master