# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run:
          command: sudo apt-get update && sudo apt-get install -y awscli
      # Set the signature version for the S3 auth
      - run:
        name: Setting Signature Version 4 for S3 Request Authentication
        command: aws configure set default.s3.signature_version s3v4
      - run: 
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync . s3://drewtestingsite --delete


#deployment:
#  prod:
#    branch: master
#    name: Deploy to S3 if tests pass and branch is Master
#    command: aws s3 sync drewtestingsite s3://drewtestingsite --delete
